version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123

    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql